# This file was generated by GoReleaser. DO NOT EDIT.
cask "drydock" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_x86_64.tar.gz"
      sha256 "d7939b65142f9cb16562c52aedffcf4c8d872742023795d7911f4c6cdb48907b"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_arm64.tar.gz"
      sha256 "353688e3d10fa80c04b9bc8d47bedf7ba1b1891bbefa5a45bc26a4f020ed8a0b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_x86_64.tar.gz"
      sha256 "8cae6ceb4b4f44225c4d1c82f3d71231d6f978fa19048d8033c4f172b430d9a5"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_arm64.tar.gz"
      sha256 "1b0a2e7aeec9ff07bcd9c922c5eff2a7d0ec505fde8a7850d0d31f8351b37d0a"
    end
  end

  name "drydock"
  desc "Inspect helm_release value changes in a Terraform plan before you set sail."
  homepage "https://github.com/sethryder/drydock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drydock"

  # No zap stanza required

end
