# This file was generated by GoReleaser. DO NOT EDIT.
cask "drydock" do
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_x86_64.tar.gz"
      sha256 "1a567e6b610273041318e0a29288bbf23d96b3b16852af137788b0875c5c5110"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_arm64.tar.gz"
      sha256 "6bf20881d82620616f36030335268104001acbdc91f14edfb861bf39ddb32471"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_x86_64.tar.gz"
      sha256 "6914500d53bf5210c563fce07063930264e0e453ef37f1151bc0710f4c1981e7"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_arm64.tar.gz"
      sha256 "b794f56a3fc863fc27ef2e2ffda0f975ee96c0f06e04a71eb5e1265734b58cbc"
    end
  end

  name "drydock"
  desc "Inspect helm_release value changes in a Terraform plan before you set sail."
  homepage "https://github.com/sethryder/drydock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drydock"

  # No zap stanza required

end
