# This file was generated by GoReleaser. DO NOT EDIT.
cask "drydock" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_x86_64.tar.gz"
      sha256 "8522d0d21c64ac457fc53c9b6b2901336947057579ae9a55ffc8c1a967a74c97"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Darwin_arm64.tar.gz"
      sha256 "4b38868a3b80d2e0b6db5fb0269fa13e22d9f7542fea7266a6edd446fbafe08a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_x86_64.tar.gz"
      sha256 "bd0cfc3d7422bc913c5e584256e6fee397cfe34cdb8a9a97f231fc54604cc4e4"
    end
    on_arm do
      url "https://github.com/sethryder/drydock/releases/download/v#{version}/drydock_#{version}_Linux_arm64.tar.gz"
      sha256 "fe6bfdbc5b78ff2fdc3d1f30cad29fd4c8d84ea95c39c55ea487b3e338f4a26f"
    end
  end

  name "drydock"
  desc "Inspect helm_release value changes in a Terraform plan before you set sail."
  homepage "https://github.com/sethryder/drydock"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drydock"

  # No zap stanza required

end
