# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drydock < Formula
  desc "Inspect helm_release value changes in a Terraform plan before you set sail."
  homepage "https://github.com/sethryder/drydock"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sethryder/drydock/releases/download/v0.1.1/drydock_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "742bbe0dcb20f1c2985a04a559155df699861a4904e30c2ff5e14ca7af00472d"

      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sethryder/drydock/releases/download/v0.1.1/drydock_0.1.1_Darwin_arm64.tar.gz"
      sha256 "5692899cb78e1f5683f963aa8b8ab3a2dd7e7fb3d0d098ee2f7cfa620aaadd8c"

      define_method(:install) do
        bin.install "drydock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethryder/drydock/releases/download/v0.1.1/drydock_0.1.1_Linux_x86_64.tar.gz"
      sha256 "8bd3ef9277ffa68016647a1070f714c5ec990e459d9488012b406acfcf026488"
      define_method(:install) do
        bin.install "drydock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sethryder/drydock/releases/download/v0.1.1/drydock_0.1.1_Linux_arm64.tar.gz"
      sha256 "bfad838ea95013e5a0776aa588dd4beddd99e8d7fac59fd52f6225b878fdc462"
      define_method(:install) do
        bin.install "drydock"
      end
    end
  end

  test do
    assert_match "drydock", shell_output("#{bin}/drydock --version")
  end
end
